gamestore/gamestore/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
]

gamestore/store/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('account/login/', auth_views.LoginView.as_view(), name='login'),
    path('account/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('account/register/', views.registration, name="register"),
    path('account/profile/', views.profile_view, name="profile_view"),
    path('game/registration/', views.register_game, name="register_game"),
    path('leaderboard/<game_title>/', views.leaderboard, name='leaderboard'),
    path('play/<game_title>/', views.play, name='play'),
    path('store/', views.store, name='store'),
    path('library/', views.library, name='library'),
    path('purchase/<game_title>', views.payment, name='payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/cancel/', views.payment_cancel, name='payment_cancel'),
    path('payment/error/', views.payment_error, name='payment_error')
]

website/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

gamestore/store/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_developer = models.BooleanField("Developer", default=False)


class Game(models.Model):
    title = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=200)
    thumbnail = models.URLField(max_length=200, blank=True)
    url = models.URLField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    developer = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, blank=True)
    purchases = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    date = models.DateTimeField(auto_now_add=True)


class Highscore(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)

    class Meta:
        ordering=['-score']

gamestore/store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Game


class RegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'password1', 'password2', 'is_developer',)


class GameRegistrationForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('title', 'description', 'thumbnail', 'url', 'price',)

gamestore/store/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required

from store.decorators import developer_required
from .forms import RegistrationForm, GameRegistrationForm
from .models import Game, Payment, Highscore
from hashlib import md5
import json


def homepage(request):
    all_games = Game.objects.all()
    featured_games = all_games[:3]
    return render(request, 'store/homepage.html', {
        'featured_games': featured_games
    })


def store(request):
    user = request.user
    all_games = Game.objects.all()
    if user.is_anonymous:
        return render(request, 'store/store.html', {
            'game_set': all_games
        })
    else:
        all_games = Game.objects.all()
        return render(request, 'store/store.html', context={
            'game_set': all_games,
        })


def library(request):
    user = request.user
    if user.is_anonymous:
        return render(request, 'store/library.html')
    else:
        purchased_games = Game.objects.filter(payment__user=user)
        developer_games = Game.objects.filter(developer=user)
        return render(request, 'store/library.html', {
            'purchased_games': purchased_games,
            'developer_games': developer_games
        })


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return redirect('homepage')
    else:
        form = RegistrationForm
    return render(request, 'registration/register.html', {
        'form': form
    })


@login_required()
def profile_view(request):
    user = request.user
    if user.is_anonymous:
        return redirect('homepage')
    else:
        payments = Payment.objects.filter(user=user)
        developer_games = Game.objects.filter(developer=user)
        total_revenue = 0
        for game in developer_games:
            total = game.price * game.purchases
            game.total = total
            total_revenue += total
        return render(request, 'store/profile.html', {
            'user': user,
            'payments': payments,
            'developer_games': developer_games,
            'total_revenue': total_revenue
        })


@login_required()
def payment(request, game_title):
    user = request.user
    game = Game.objects.get(title=game_title)
    if not Payment.objects.filter(user=user, game=game).exists() and not Game.objects.filter(id=game.id, developer=user).exists():
        pid = str(game.pk)
        sid = '43124917'
        amount = game.price
        success_url = request.build_absolute_uri(reverse('payment_success'))
        print(success_url)
        cancel_url = request.build_absolute_uri(reverse('payment_cancel'))
        error_url = request.build_absolute_uri(reverse('payment_error'))
        secret_key = 'ea22e857acbfe3653cad46f2d70b99d5'
        checksumstr = "pid={}&sid={}&amount={}&token={}".format(pid, sid, amount, secret_key)
        m = md5(checksumstr.encode("ascii"))
        checksum = m.hexdigest()
        payment_details = {
            'pid': pid,
            'sid': sid,
            'amount': amount,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'error_url': error_url,
            'checksum': checksum
        }
        return render(request, 'payment/verification.html', {'payment_details': payment_details})
    else:
        return render(request, 'payment/ownership_message.html')

@login_required()
def payment_success(request):
    if request.method == 'GET':
        checksum = request.GET.get('checksum', '')
        pid = request.GET.get('pid', '')
        ref = request.GET.get('ref', '')
        result = request.GET.get('result', '')
        secret_key = 'ea22e857acbfe3653cad46f2d70b99d5'
        checksumstr = "pid={}&ref={}&result={}&token={}".format(pid, ref, result, secret_key)
        m = md5(checksumstr.encode('ascii'))
        calc_checksum = m.hexdigest()
        if checksum == calc_checksum:
            user = request.user
            game = Game.objects.get(id=pid)
            if not Payment.objects.filter(user=user, game=game).exists():
                new_payment = Payment(
                    user=user,
                    game=game,
                    amount=game.price
                )
                new_payment.save()
            Game.objects.filter(id=game.id).update(purchases=game.purchases+1)
            return render(request, 'payment/success.html', {
                'pid': pid,
                'ref': ref,
            })

    return HttpResponseBadRequest('Invalid checksum')

@login_required()
def payment_cancel(request):
    return render(request, 'payment/cancel.html')

def payment_error(request):
    return render(request, 'payment/error.html')


@developer_required()
def register_game(request):
    if request.method == 'POST':
        form = GameRegistrationForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.developer = request.user
            if not f.thumbnail:
                f.thumbnail = 'https://i.imgur.com/LLxYUgy.png'
            f.save()
            return redirect('store')
    else:
        form = GameRegistrationForm()

    return render(request, 'game/register_game.html', {'form': form})


@login_required
def play(request, game_title):
    user = request.user
    game = Game.objects.get(title=game_title)
    if Payment.objects.filter(user=user,game=game).exists() or Game.objects.filter(id=game.id, developer=user).exists():
        highscore = Highscore.objects.filter(game=game)
        top_5 = highscore[:5]
        if request.method == 'GET':
            #When you are redirected to an url it loads the game
            return render(request,"game/play.html", {
                'game_title': game.title,
                'remote_server': game.url,
                'top_highscores': top_5
            })
        elif request.method == 'POST':
            #TODO: add methods that add scores and saved games to db
            #remove current render when done just here so the server can be run
            score = request.POST.get('Score')
            save = Highscore.objects.create(user=request.user , game=game, score=score)
            #save.save()
            reposnse_data = {}
            reposnse_data['result'] = 'Score saved successfully'
            reposnse_data['score'] = score
            reposnse_data['user'] = request.user.username
            return HttpResponse(
                json.dumps(reposnse_data),
                content_type="application/json"
            )
    else:
        return HttpResponseBadRequest('Access denied')

@login_required
def leaderboard(request, game_title):
    game = Game.objects.get(title=game_title)
    highscore = Highscore.objects.filter(game=game)
    return render(request, 'game/leaderboard.html', {
        'game_title': game.title,
        'highscores': highscore
    })

gamestore/store/templates/game/Leaderboard.html
{% extends 'store/base.html' %}

{% block title %}{{ game_title }} - Leaderboard{% endblock %}

{% block content %}

<div class="text-center mt-5" class="mt-5">
  <div style="display: inline-block; color: darkslategrey;">
    <h2>{{ game_title }} Leaderboard</h2>
    {% if highscores %}
      <table class="table">
        <tr>
          <th>Rank</th>
          <th>Username</th>
          <th>Score</th>
        </tr>
        {% for score in highscores %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ score.user }}</td>
          <td>{{ score.score }}</td>
        </tr>
        {% endfor %}
      </table>
    {% else %}
      <div class="text-left" style="display: inline-block;">
        <p><strong>No highscores yet</strong></a></p>
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

gamestore/store/templates/game/leaderboard.html
{% extends 'store/base.html' %}

{% block title %}{{ game_title }} - Leaderboard{% endblock %}

{% block content %}

<div class="text-center mt-5" class="mt-5">
  <div style="display: inline-block; color: darkslategrey;">
    <h2>{{ game_title }} Leaderboard</h2>
    {% if highscores %}
      <table class="table">
        <tr>
          <th>Rank</th>
          <th>Username</th>
          <th>Score</th>
        </tr>
        {% for score in highscores %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ score.user }}</td>
          <td>{{ score.score }}</td>
        </tr>
        {% endfor %}
      </table>
    {% else %}
      <div class="text-left" style="display: inline-block;">
        <p><strong>No highscores yet</strong></a></p>
      </div>
    {% endif %}
  </div>
</div>
{% endblock %}

gamestore/store/templates/game/play.html
{% extends "store/base.html" %}

{% block title %}Gamestore - GameTitle{% endblock %}

{% block content %}
<div class="p-5 row">
    <div class="col-md-9 embed-responsive embed-responsive-16by9">
        <iframe id="iframe" class="embed-responsive-item" src="{{ remote_server }}"></iframe>
    </div>
    <div class="col-md-3 text-center">
        {% if top_highscores %}
        <h3>Top 5</h3>
        <table class="table">
            <tr>
                <th>Rank</th>
                <th>Username</th>
                <th>Score</th>
            </tr>
            {% for score in top_highscores %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ score.user }}</td>
                <td>{{ score.score }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        <p>Show all <a href="{% url 'leaderboard' game_title=game_title %}">Highscores</a></p>
        <p>Your last score: <span id='lastscore'>0</span></p>
    </div>
</div>



    <script type="text/javascript">
        window.addEventListener("message", reciver, false)

        function reciver(e) {
            var gamescore = parseInt(e.data.score);
            var middlewaretoken = "{{ csrf_token  }}";
            var message = {messageType: "ERROR"};
            if(e.data.messageType === "SCORE")
                $('#lastscore').text(gamescore);

            if (e.data.messageType === "SETTING") {
                var width = e.data.options.width;
                var height = e.data.options.height;
                if(!isNaN(width)){
                    if(width>800){
                        width = 800;
                    }else if(width<40){
                        width = 40;
                    }
                    $('#iframe').css('width',width);
                }
                if(!isNaN(height)){
                    if(height>600){
                        height = 600;
                    }else if(height<40){
                        height = 40;
                    }
                    $('#iframe').css('height',height);
                }
            }
            else if(e.data.messageType === "SCORE")

                $.ajax({
                    url: "#",
                    type: "POST",
                    data: {Score: gamescore, csrfmiddlewaretoken: middlewaretoken},
                    
                    success: function() {
                        console.log(e.data);
                        console.log("success");
                        message.info = "You submitted score";
                        document.getElementById('iframe').contentWindow.postMessage(message,'*');
                    },
                    error : function(xhr,errmsg,err) {
                        console.log(errmsg);
                        console.log(xhr.status + ": " + xhr.responseText);
                }});
            else if(e.data.messageType === "SAVE")
                alert(e.data.gameState.score);
            else if(e.data.messageType === "LOAD")
                alert(e.data.messageType);
            else if(e.data.messageType === "LOAD_REQUEST")
                alert(e.data.messageType);

            //console.log(e);
        };
    </script>
{% endblock %}

gamestore/store/templates/game/register_game.html
{% extends "store/base.html" %}

{% block title %}Gamestore - Add Game{% endblock %}

{% block content %}

<main role="main">
  <div class="justify-content-center row">
    <div class="col-md-5" style="margin-top:20vh">
      <form method="post" action="{% url 'register_game' %}">
        {% csrf_token %}
        {% if form.errors %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
          <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
          <strong>{{ error|escape }}</strong>
        </div>
        {% endfor %}
        {% endif %}
        <input class="form-control" type="text" name="title" maxlength="50" required="" placeholder="Title" id="id_title">
        <input class="form-control mt-1" type="text" name="description" maxlength="200" required="" placeholder="Description">
        <input class="form-control mt-2" type="url" name="thumbnail" maxlength="200" placeholder="Thumbnail URL (Optional)">
        <input class="form-control mt-2" type="url" name="url" maxlength="200" required="" placeholder="Game URL">
        <label class="mt-1 mb-1" for="id_price" style="color: darkslategrey">Price</label>
        <input class="form-control" type="number" name="price" value="0" step="0.01" required="" id="id_price">
        <button class="form-control mt-2 btn btn-sm btn-outline-secondary" type="submit">Register</button>
      </form>
    </div>
  </div>
</main>

{% endblock %}