gamestore/gamestore/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('store.urls')),
    path('admin/', admin.site.urls),
]

gamestore/store/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('account/login/', auth_views.LoginView.as_view(), name='login'),
    path('account/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('account/register/', views.registration, name="register"),
    path('account/profile/', views.profile_view, name="profile_view"),
    path('game/registration/', views.register_game, name="register_game"),
    path('leaderboard/<game_title>/', views.leaderboard, name='leaderboard'),
    path('play/<game_title>/', views.play, name='play'),
    path('store/', views.store, name='store'),
    path('library/', views.library, name='library'),
    path('purchase/<game_title>', views.payment, name='payment'),
    path('payment/success/', views.payment_success, name='payment_success'),
    path('payment/cancel/', views.payment_cancel, name='payment_cancel'),
    path('payment/error/', views.payment_error, name='payment_error')
]

website/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

gamestore/store/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    is_developer = models.BooleanField("Developer", default=False)


class Game(models.Model):
    title = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=200)
    thumbnail = models.URLField(max_length=200, blank=True)
    url = models.URLField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    developer = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, blank=True)
    purchases = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    date = models.DateTimeField(auto_now_add=True)


class Highscore(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)

    class Meta:
        ordering=['-score']

gamestore/store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Game


class RegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'password1', 'password2', 'is_developer',)


class GameRegistrationForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('title', 'description', 'thumbnail', 'url', 'price',)

gamestore/store/views.py
from django.http import HttpResponse, HttpResponseBadRequest
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required

from store.decorators import developer_required
from .forms import RegistrationForm, GameRegistrationForm
from .models import Game, Payment, Highscore
from hashlib import md5
import json


def homepage(request):
    all_games = Game.objects.all()
    featured_games = all_games[:3]
    return render(request, 'store/homepage.html', {
        'featured_games': featured_games
    })


def store(request):
    user = request.user
    all_games = Game.objects.all()
    if user.is_anonymous:
        return render(request, 'store/store.html', {
            'game_set': all_games
        })
    else:
        all_games = Game.objects.all()
        return render(request, 'store/store.html', context={
            'game_set': all_games,
        })


def library(request):
    user = request.user
    if user.is_anonymous:
        return render(request, 'store/library.html')
    else:
        purchased_games = Game.objects.filter(payment__user=user)
        developer_games = Game.objects.filter(developer=user)
        return render(request, 'store/library.html', {
            'purchased_games': purchased_games,
            'developer_games': developer_games
        })


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return redirect('homepage')
    else:
        form = RegistrationForm
    return render(request, 'registration/register.html', {
        'form': form
    })


@login_required()
def profile_view(request):
    user = request.user
    if user.is_anonymous:
        return redirect('homepage')
    else:
        payments = Payment.objects.filter(user=user)
        developer_games = Game.objects.filter(developer=user)
        total_revenue = 0
        for game in developer_games:
            total = game.price * game.purchases
            game.total = total
            total_revenue += total
        return render(request, 'store/profile.html', {
            'user': user,
            'payments': payments,
            'developer_games': developer_games,
            'total_revenue': total_revenue
        })


@login_required()
def payment(request, game_title):
    user = request.user
    game = Game.objects.get(title=game_title)
    if not Payment.objects.filter(user=user, game=game).exists() and not Game.objects.filter(id=game.id, developer=user).exists():
        pid = str(game.pk)
        sid = '43124917'
        amount = game.price
        success_url = request.build_absolute_uri(reverse('payment_success'))
        print(success_url)
        cancel_url = request.build_absolute_uri(reverse('payment_cancel'))
        error_url = request.build_absolute_uri(reverse('payment_error'))
        secret_key = 'ea22e857acbfe3653cad46f2d70b99d5'
        checksumstr = "pid={}&sid={}&amount={}&token={}".format(pid, sid, amount, secret_key)
        m = md5(checksumstr.encode("ascii"))
        checksum = m.hexdigest()
        payment_details = {
            'pid': pid,
            'sid': sid,
            'amount': amount,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'error_url': error_url,
            'checksum': checksum
        }
        return render(request, 'payment/verification.html', {'payment_details': payment_details})
    else:
        return render(request, 'payment/ownership_message.html')

@login_required()
def payment_success(request):
    if request.method == 'GET':
        checksum = request.GET.get('checksum', '')
        pid = request.GET.get('pid', '')
        ref = request.GET.get('ref', '')
        result = request.GET.get('result', '')
        secret_key = 'ea22e857acbfe3653cad46f2d70b99d5'
        checksumstr = "pid={}&ref={}&result={}&token={}".format(pid, ref, result, secret_key)
        m = md5(checksumstr.encode('ascii'))
        calc_checksum = m.hexdigest()
        if checksum == calc_checksum:
            user = request.user
            game = Game.objects.get(id=pid)
            if not Payment.objects.filter(user=user, game=game).exists():
                new_payment = Payment(
                    user=user,
                    game=game,
                    amount=game.price
                )
                new_payment.save()
            Game.objects.filter(id=game.id).update(purchases=game.purchases+1)
            return render(request, 'payment/success.html', {
                'pid': pid,
                'ref': ref,
            })

    return HttpResponseBadRequest('Invalid checksum')

@login_required()
def payment_cancel(request):
    return render(request, 'payment/cancel.html')

def payment_error(request):
    return render(request, 'payment/error.html')


@developer_required()
def register_game(request):
    if request.method == 'POST':
        form = GameRegistrationForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.developer = request.user
            if not f.thumbnail:
                f.thumbnail = 'https://i.imgur.com/LLxYUgy.png'
            f.save()
            return redirect('store')
    else:
        form = GameRegistrationForm()

    return render(request, 'game/register_game.html', {'form': form})


@login_required
def play(request, game_title):
    user = request.user
    game = Game.objects.get(title=game_title)
    if Payment.objects.filter(user=user,game=game).exists() or Game.objects.filter(id=game.id, developer=user).exists():
        highscore = Highscore.objects.filter(game=game)
        top_5 = highscore[:5]
        if request.method == 'GET':
            #When you are redirected to an url it loads the game
            return render(request,"game/play.html", {
                'game_title': game.title,
                'remote_server': game.url,
                'top_highscores': top_5
            })
        elif request.method == 'POST':
            #TODO: add methods that add scores and saved games to db
            #remove current render when done just here so the server can be run
            score = request.POST.get('Score')
            save = Highscore.objects.create(user=request.user , game=game, score=score)
            #save.save()
            reposnse_data = {}
            reposnse_data['result'] = 'Score saved successfully'
            reposnse_data['score'] = score
            reposnse_data['user'] = request.user.username
            return HttpResponse(
                json.dumps(reposnse_data),
                content_type="application/json"
            )
    else:
        return HttpResponseBadRequest('Access denied')

@login_required
def leaderboard(request, game_title):
    game = Game.objects.get(title=game_title)
    highscore = Highscore.objects.filter(game=game)
    return render(request, 'game/leaderboard.html', {
        'game_title': game.title,
        'highscores': highscore
    })

gamestore/store/templates/store/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.css' %}">
    <script src="{% static 'jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.bundle.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="bg-light">
    <div class="container-fluid px-0">

        <nav class="navbar navbar-expand-sm navbar-light bg-light">
            <a class="navbar-brand ml-2" href="{% url 'homepage' %}">GameStore</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item homepage">
                        <a class="nav-link" href="{% url 'homepage' %}">Home</a>
                    </li>
                    <li class="nav-item library">
                        <a class="nav-link" href="{% url 'library' %}">Library</a>
                    </li>
                    <li class="nav-item store">
                        <a class="nav-link" href="{% url 'store' %}">Store</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Account
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if user.is_developer %}
                            <a class="dropdown-item" href="{% url 'profile_view'%}">View profile</a>
                            <a class="dropdown-item" href="{% url 'register_game' %}">Register Game</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            {% else %}
                            <a class="dropdown-item" href="{% url 'profile_view'%}">View profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            {% endif %}
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">{{ user.username }}</a>
                    </li>
                    {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Account
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Guest</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock %}

    </div>
</body>
</html>

gamestore/store/templates/store/homepage.html
{% extends "store/base.html" %}

{% block title %}Gamestore - Home{% endblock %}

{% block content %}
<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron bg-light">
    <div class="container">
      <h1 class="display-2">Welcome to GameStore</h1>
    </div>
  </div>
  <div class="jumbotron p-3">
    <div class="container">
      <h1 class="display-4">Featured games</h1>
      {% if featured_games %}
      <div class="album my-5">
        <div class="container">
          <div class="row">
            {% for game in featured_games %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow bg-light">
                <img class="card-img-top" src="{{ game.thumbnail }}" style="height: 225px; width: 100%; display: block;">
                <div class="card-body">
                  <p class="card-text"><strong>{{ game.title }}</strong><br>{{ game.description }}</p>
                </div>
              </div>
            </div>
            {% if forloop.counter|divisibleby:3 %}
          </div>
          <div class="row">
            {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
      {% else %}
      <div class="alert mt-5 pt-5" role="alert">
        <p class="text-center"><strong>No games in store yet</strong></a></p>
      </div>
      {% endif %}
    </div>
  </div>


</main>

<script>
    $("li.homepage").addClass("active")
</script>
{% endblock %}

gamestore/store/templates/store/library.html
{% extends "store/base.html" %}

{% block title %}Gamestore - Library{% endblock %}

{% block content %}
<main role="main">

{% if user.is_authenticated %}
  <!--Purchased Games-->
  {% if purchased_games %}
    <div class="album my-5 bg-light">
      <div class="container">
        <h1 class="text-center mb-3" style="color: darkslategrey;">Purchased games</h1>
          <div class="row">
            {% for game in purchased_games %}
              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                  <img class="card-img-top" src="{{ game.thumbnail }}" style="height: 225px; width: 100%; display: block;">
                  <div class="card-body">
                    <p class="card-text"><strong>{{ game.title }}</strong><br>{{ game.description }}</p>
                    <div class="row">
                        <a href="{% url 'play' game_title=game.title %}" class="btn btn-sm btn-outline-secondary offset-1 col-md-4">Play</a>
                        <a href="{% url 'leaderboard' game_title=game.title %}" class="btn btn-sm btn-outline-secondary offset-1 col-md-4">Leaderboard</a>
                    </div>
                  </div>
                </div>
              </div>
            {% if forloop.counter|divisibleby:3 %}
              </div>
              <div class="row">
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
  {% else %}
  <div class="alert mt-5 pt-5" role="alert">
    <p class="text-center"><strong>Your game library is empty.</strong> Buy games in <a href="{% url 'store' %}">store.</a></p>
  </div>
  {% endif %}

  {% if developer_games %}
    <div class="album my-5 bg-light">
      <div class="container">
        <h1 class="text-center mb-3" style="color: darkslategrey;">My games</h1>
        <div class="row">
          {% for game in developer_games %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" src="{{ game.thumbnail }}" style="height: 225px; width: 100%; display: block;">
              <div class="card-body">
                <p class="card-text"><strong>{{ game.title }}</strong><br>{{ game.description }}</p>
                <div class="row">
                  <a href="{% url 'play' game_title=game.title %}" class="btn btn-sm btn-outline-secondary offset-1 col-md-4">Play</a>
                  <a href="{% url 'leaderboard' game_title=game.title %}" class="btn btn-sm btn-outline-secondary offset-1 col-md-4">Leaderboard</a>
                </div>
              </div>
            </div>
          </div>
          {% if forloop.counter|divisibleby:3 %}
        </div>
        <div class="row">
          {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
  {% endif %}

{% else %}
  <div class="alert mt-5 pt-5" role="alert">
    <p class="text-center">Please <a href="{% url 'login' %}">log in</a> to view library content</p>
  </div>
{% endif %}

</main>

<script>
    $("li.library").addClass("active")
</script>
{% endblock %}

gamestore/store/templates/store/profile.html
{% extends "store/base.html" %}

{% block title %}Gamestore - My profile{% endblock %}

{% block content %}
<div class="ml-5 mt-5">
  <div class="text-left" style="display: inline-block;">
    <h3>Account details</h3>
    <p><strong>Username: </strong>{{ user.username}}</p>
    <h3>Payments</h3>
    {% if payments %}
      <table class="table">
        <tr>
          <th>ID</th>
          <th>Game</th>
          <th>Amount</th>
          <th>Date</th>
        </tr>
      {% for payment in payments %}
        <tr>
          <td>{{ payment.id }}</td>
          <td>{{ payment.game }}</td>
          <td>{{ payment.amount }}</td>
          <td>{{ payment.date }}</td>
        </tr>
      {% endfor %}
      </table>
    {% else %}
    <p>You have no payments</p>
    {% endif %}
    {% if user.is_developer %}
    <h3>Sale stats</h3>
    {% if developer_games %}
    <table class="table">
      <tr>
        <th>Game</th>
        <th>Purchases</th>
        <th>Price</th>
        <th>Total</th>
      </tr>
      {% for game in developer_games %}
      <tr>
        <td>{{ game.title }}</td>
        <td>{{ game.purchases }}</td>
        <td>{{ game.price }}</td>
        <td>{{ game.total }}</td>
      </tr>
      {% endfor %}
      <tfoot>
        <td colspan="4">Total revenue: {{ total_revenue }}</td>
      </tfoot>
    </table>
    {% else %}
    <p>You have no sold games</p>
    {% endif %}
    {% endif %}
  </div>
</div>
{% endblock %}

gamestore/store/templates/store/register_game.html
{% extends "store/base.html" %}

{% block title %}Gamestore - Add Game{% endblock %}

{% block content %}

<main role="main">
  <div class="justify-content-center row">
    <div style="display: inline-block; margin-top: 25vh">
      <form method="post" enctype="multipart/form-data" action="{% url 'register_game' %}">
        {% csrf_token %}
        <input class="form-control" type="text" name="title" maxlength="50" required="" placeholder="title">
        <input class="form-control mt-1" type="text" name="description" maxlength="200" required="" placeholder="Description">
        <div class="form-group">
          <label class="mt-2 mb-1" for="id_thumbnail" style="color: darkslategrey">Thumbnail</label>
          <input class="form-control-file" type="file" name="thumbnail" id="id_thumbnail">
          <small id="fileHelp" class="form-text text-muted">Picture ratio preferrably 2:1 </small>
        </div>
        <input class="form-control mt-2" type="url" name="url" maxlength="200" required="" placeholder="Url">
        <label class="mt-1 mb-1" for="id_price" style="color: darkslategrey">Price</label>
        <input class="form-control" type="number" name="price" value="0" step="0.01" required="" id="id_price">
        <button class="form-control mt-2 btn btn-sm btn-outline-secondary" type="submit">Register</button>
      </form>
    </div>
  </div>
</main>

{% endblock %}

gamestore/store/templates/store/store.html
{% extends "store/base.html" %}

{% block title %}Gamestore - Store{% endblock %}

{% block content %}
<main role="main">

{% if game_set %}
  <div class="album my-5 bg-light">
    <div class="container">
    <h1 class="text-center mb-3" style="color: darkslategrey;">All games</h1>
    <div class="row">
    {% for game in game_set %}
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <img class="card-img-top" src="{{ game.thumbnail }}" style="height: 225px; width: 100%; display: block;">
              <div class="card-body">
                <p class="card-text"><strong>{{ game.title }}</strong><br>{{ game.description }}</p>
                <div class="row">
                  <a href="{% url 'payment' game_title=game.title %}" class="btn btn-sm btn-outline-secondary ml-3">Purchase</a>
                  <p class="ml-3 mt-1 mb-0" style="color: darkslategrey">{{ game.price}} $</p>
                </div>
              </div>
            </div>
          </div>
      {% if forloop.counter|divisibleby:3 %}
        </div>
        <div class="row">
      {% endif %}
    {% endfor %}
    </div>
    </div>
  </div>
{% else %}
  <div class="alert mt-5 pt-5" role="alert">
    <p class="text-center"><strong>Sorry!</strong> No games available in store</p>
  </div>
{% endif %}

</main>

<script>
    $("li.store").addClass("active")
</script>

{% endblock %}